// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epbkxsivbiloxagzgocm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwYmt4c2l2Ymlsb3hhZ3pnb2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTQyNzcsImV4cCI6MjA3Mzk3MDI3N30.hrMgtaNPlBnKM7oEihOtZRQzHjzsdno23FAh_V8rPvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});